# Generated by Django 5.2.6 on 2025-09-21 16:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('detection_data', models.JSONField(help_text='JSON data containing detection results')),
                ('image_or_video_ref', models.CharField(blank=True, help_text='Reference to stored image/video file or base64 data', max_length=500, null=True)),
                ('detection_type', models.CharField(choices=[('image', 'Image Detection'), ('video', 'Video Detection'), ('live', 'Live Feed Detection')], default='live', max_length=20)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('objects_detected', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection History',
                'verbose_name_plural': 'Detection Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
